"""add presence fields

Revision ID: 18fee14ce212
Revises: f1d2d74c8a7b
Create Date: 2025-07-24 14:52:50.858644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18fee14ce212'
down_revision: Union[str, Sequence[str], None] = 'f1d2d74c8a7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inscricoes_treinamento', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'presenca_teoria',
                sa.Boolean(),
                nullable=False,
                server_default=sa.text('false'),
            )
        )
        batch_op.add_column(
            sa.Column(
                'presenca_pratica',
                sa.Boolean(),
                nullable=False,
                server_default=sa.text('false'),
            )
        )
        batch_op.alter_column('usuario_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('turmas_treinamento', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('turmas_treinamento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'aberta'"), nullable=False))

    with op.batch_alter_table('inscricoes_treinamento', schema=None) as batch_op:
        batch_op.alter_column('usuario_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('presenca_pratica')
        batch_op.drop_column('presenca_teoria')

    # ### end Alembic commands ###
