"""add timestamp fields to suporte_chamados

Revision ID: 892341234567
Revises: 2f5d1f0614c3
Create Date: 2025-11-20 00:30:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '892341234567'
down_revision = '2f5d1f0614c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('suporte_chamados', schema=None) as batch_op:
        batch_op.add_column(sa.Column('inicio_atendimento_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('encerrado_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('suporte_chamados', schema=None) as batch_op:
        batch_op.drop_column('encerrado_at')
        batch_op.drop_column('inicio_atendimento_at')

    # ### end Alembic commands ###
