"""create treinamento models

Revision ID: 933546544697
Revises: 
Create Date: 2025-07-22 12:22:15.080137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '933546544697'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instrutores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('area_atuacao', sa.String(length=100), nullable=True),
    sa.Column('disponibilidade', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('data_atualizacao', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('laboratorios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('classe_icone', sa.String(length=50), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('data_atualizacao', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('log_lancamentos_rateio_instrutor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('acao', sa.String(length=20), nullable=True),
    sa.Column('usuario', sa.String(length=100), nullable=True),
    sa.Column('instrutor', sa.String(length=100), nullable=True),
    sa.Column('filial', sa.String(length=100), nullable=True),
    sa.Column('uo', sa.String(length=100), nullable=True),
    sa.Column('cr', sa.String(length=100), nullable=True),
    sa.Column('classe_valor', sa.String(length=100), nullable=True),
    sa.Column('percentual', sa.Float(), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('logs_agendamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario', sa.String(length=100), nullable=True),
    sa.Column('tipo_acao', sa.String(length=20), nullable=True),
    sa.Column('laboratorio', sa.String(length=50), nullable=True),
    sa.Column('turno', sa.String(length=20), nullable=True),
    sa.Column('data_agendamento', sa.Date(), nullable=True),
    sa.Column('dados_antes', sa.JSON(), nullable=True),
    sa.Column('dados_depois', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rateio_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filial', sa.String(length=100), nullable=False),
    sa.Column('unidade_organizacional', sa.String(length=100), nullable=False),
    sa.Column('centro_resultado', sa.String(length=100), nullable=False),
    sa.Column('classe_valor', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('filial', 'unidade_organizacional', 'centro_resultado', 'classe_valor', name='_rateio_config_uc')
    )
    op.create_table('recursos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('salas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('capacidade', sa.Integer(), nullable=False),
    sa.Column('localizacao', sa.String(length=100), nullable=True),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('data_atualizacao', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('treinamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('capacidade_maxima', sa.Integer(), nullable=True),
    sa.Column('carga_horaria', sa.Integer(), nullable=True),
    sa.Column('tem_pratica', sa.Boolean(), nullable=True),
    sa.Column('links_materiais', sa.JSON(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('data_atualizacao', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('turmas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('data_atualizacao', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('senha_hash', sa.String(length=256), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('data_atualizacao', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('agendamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('laboratorio', sa.String(length=50), nullable=False),
    sa.Column('turma', sa.String(length=50), nullable=False),
    sa.Column('turno', sa.String(length=20), nullable=False),
    sa.Column('horarios', sa.JSON(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('data_atualizacao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=True),
    sa.Column('entity', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lancamentos_rateio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrutor_id', sa.Integer(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('rateio_config_id', sa.Integer(), nullable=False),
    sa.Column('percentual', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['instrutor_id'], ['instrutores.id'], ),
    sa.ForeignKeyConstraint(['rateio_config_id'], ['rateio_configs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lancamentos_rateio', schema=None) as batch_op:
        batch_op.create_index('ix_lancamento_instrutor_periodo', ['instrutor_id', 'ano', 'mes'], unique=False)
        batch_op.create_index(batch_op.f('ix_lancamentos_rateio_instrutor_id'), ['instrutor_id'], unique=False)

    op.create_table('ocupacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sala_id', sa.Integer(), nullable=False),
    sa.Column('instrutor_id', sa.Integer(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('curso_evento', sa.String(length=200), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('horario_inicio', sa.Time(), nullable=False),
    sa.Column('horario_fim', sa.Time(), nullable=False),
    sa.Column('grupo_ocupacao_id', sa.String(length=36), nullable=True),
    sa.Column('tipo_ocupacao', sa.String(length=50), nullable=True),
    sa.Column('recorrencia', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('data_atualizacao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['instrutor_id'], ['instrutores.id'], ),
    sa.ForeignKeyConstraint(['sala_id'], ['salas.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ocupacoes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ocupacoes_grupo_ocupacao_id'), ['grupo_ocupacao_id'], unique=False)

    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_table('sala_recursos',
    sa.Column('sala_id', sa.Integer(), nullable=False),
    sa.Column('recurso_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['recurso_id'], ['recursos.id'], ),
    sa.ForeignKeyConstraint(['sala_id'], ['salas.id'], ),
    sa.PrimaryKeyConstraint('sala_id', 'recurso_id')
    )
    op.create_table('turmas_treinamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('treinamento_id', sa.Integer(), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_termino', sa.Date(), nullable=False),
    sa.Column('data_treinamento_pratico', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['treinamento_id'], ['treinamentos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inscricoes_treinamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('turma_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('cpf', sa.String(length=20), nullable=False),
    sa.Column('data_nascimento', sa.Date(), nullable=True),
    sa.Column('empresa', sa.String(length=150), nullable=True),
    sa.Column('data_inscricao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['turma_id'], ['turmas_treinamento.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notificacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('agendamento_id', sa.Integer(), nullable=True),
    sa.Column('mensagem', sa.String(length=255), nullable=False),
    sa.Column('lida', sa.Boolean(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agendamento_id'], ['agendamentos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notificacoes')
    op.drop_table('inscricoes_treinamento')
    op.drop_table('turmas_treinamento')
    op.drop_table('sala_recursos')
    op.drop_table('refresh_tokens')
    with op.batch_alter_table('ocupacoes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ocupacoes_grupo_ocupacao_id'))

    op.drop_table('ocupacoes')
    with op.batch_alter_table('lancamentos_rateio', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lancamentos_rateio_instrutor_id'))
        batch_op.drop_index('ix_lancamento_instrutor_periodo')

    op.drop_table('lancamentos_rateio')
    op.drop_table('audit_logs')
    op.drop_table('agendamentos')
    op.drop_table('usuarios')
    op.drop_table('turmas')
    op.drop_table('treinamentos')
    op.drop_table('salas')
    op.drop_table('recursos')
    op.drop_table('rateio_configs')
    op.drop_table('logs_agendamentos')
    op.drop_table('log_lancamentos_rateio_instrutor')
    op.drop_table('laboratorios')
    op.drop_table('instrutores')
    # ### end Alembic commands ###
