"""add fields to turma treinamento

Revision ID: e5b8e9f1a2c3
Revises: 0c016820b114
Create Date: 2025-07-23 22:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5b8e9f1a2c3'
down_revision: Union[str, Sequence[str], None] = '0c016820b114'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('turmas_treinamento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('local_realizacao', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('horario', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('instrutor_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_turmas_instrutor', 'instrutores', ['instrutor_id'], ['id'])
        batch_op.drop_column('data_treinamento_pratico')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('turmas_treinamento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_treinamento_pratico', sa.DATE(), nullable=True))
        batch_op.drop_constraint('fk_turmas_instrutor', type_='foreignkey')
        batch_op.drop_column('instrutor_id')
        batch_op.drop_column('horario')
        batch_op.drop_column('local_realizacao')

    # ### end Alembic commands ###
